// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGnzS61Ka4lQ87GKtNLSDh9HM_9Yyur4w',
    appId: '1:339534952888:android:4552183e9f9f53c524774d',
    messagingSenderId: '339534952888',
    projectId: 'able-me-24704',
    databaseURL: 'https://able-me-24704-default-rtdb.firebaseio.com',
    storageBucket: 'able-me-24704.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgbcROXD5YbfeSZbN4F_jqqL80FDeiolg',
    appId: '1:339534952888:ios:950447ee454bb91224774d',
    messagingSenderId: '339534952888',
    projectId: 'able-me-24704',
    databaseURL: 'https://able-me-24704-default-rtdb.firebaseio.com',
    storageBucket: 'able-me-24704.appspot.com',
    androidClientId: '339534952888-5mijsecq65hgn0oh33qol955msd2mlr1.apps.googleusercontent.com',
    iosClientId: '339534952888-3oriesj03qv9n2qk3pt13hmoi0qpbpjt.apps.googleusercontent.com',
    iosBundleId: 'com.alnaughtech.ableMe',
  );

}